CREATE TABLE IF NOT EXISTS ai_agent_answerable_question (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY COMMENT '主键',
  `organization_id` VARCHAR(64) NOT NULL COMMENT '组织 ID',
  `question` VARCHAR(1024) NOT NULL COMMENT '标准问题，用于代表一类可回答问题',
  `question_aliases` JSON NULL COMMENT '相似问法列表 JSON，例如用户可能的不同提问方式',
  `normalized_question` VARCHAR(1024) NULL COMMENT '归一化后的问题文本，用于关键词检索或向量检索',
  `category` VARCHAR(64) NULL COMMENT '问题分类，例如客户、订单、沟通、权限、系统配置',
  `tags` JSON NULL COMMENT '问题标签 JSON',
  `answer_type` VARCHAR(32) NOT NULL DEFAULT 'STATIC' COMMENT '回答类型：STATIC=固定答案；TEMPLATE=模板答案；TOOL=工具动态查询；LLM=大模型生成',
  `answer` LONGTEXT NULL COMMENT '固定答案或回答模板；动态查询类问题可存回答格式模板',
  `intent` VARCHAR(128) NULL COMMENT '业务意图，例如 sales_customer_communication_list',
  `tool_name` VARCHAR(128) NULL COMMENT '动态查询时要调用的工具名称',
  `tool_params_json` JSON NULL COMMENT '工具参数模板 JSON，例如销售人员、客户名称、时间范围等槽位',
  `data_sources` JSON NULL COMMENT '回答依赖的数据源列表 JSON，例如 customer、wecom_ingestion_message、email_webhook_event',
  `match_threshold` DECIMAL(5, 4) NOT NULL DEFAULT 0.8000 COMMENT '匹配命中阈值，达到该分数才认为可以回答',
  `status` VARCHAR(32) NOT NULL DEFAULT 'ENABLED' COMMENT '启用状态：ENABLED=启用；DISABLED=停用',
  `review_status` VARCHAR(32) NOT NULL DEFAULT 'APPROVED' COMMENT '审核状态：DRAFT=草稿；APPROVED=已确认可用',
  `hit_count` BIGINT NOT NULL DEFAULT 0 COMMENT '被匹配命中的次数',
  `last_hit_time` BIGINT NULL COMMENT '最后一次命中时间（毫秒时间戳）',
  `remark` VARCHAR(1024) NULL COMMENT '备注说明',
  `create_user` VARCHAR(64) NULL COMMENT '创建人 ID',
  `update_user` VARCHAR(64) NULL COMMENT '最后修改人 ID',
  `create_time` BIGINT NOT NULL COMMENT '创建时间（毫秒时间戳）',
  `update_time` BIGINT NOT NULL COMMENT '更新时间（毫秒时间戳）',
  INDEX idx_ai_agent_answerable_org_status (`organization_id`, `status`, `review_status`),
  INDEX idx_ai_agent_answerable_intent (`organization_id`, `intent`),
  INDEX idx_ai_agent_answerable_question (`organization_id`, `normalized_question`(191)),
  INDEX idx_ai_agent_answerable_update (`organization_id`, `update_time`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI Agent 可回答问题库：保存标准问题、固定答案、动态查询规则和匹配配置';

CREATE TABLE IF NOT EXISTS ai_agent_unanswered_question (
  `id` VARCHAR(64) NOT NULL PRIMARY KEY COMMENT '主键',
  `organization_id` VARCHAR(64) NOT NULL COMMENT '组织 ID',
  `user_id` VARCHAR(64) NULL COMMENT '提问用户 ID',
  `session_id` VARCHAR(64) NULL COMMENT '来源会话 ID，关联 ai_agent_session.id',
  `message_id` VARCHAR(64) NULL COMMENT '来源用户消息 ID，关联 ai_agent_message.id',
  `question` VARCHAR(1024) NOT NULL COMMENT '用户原始问题',
  `normalized_question` VARCHAR(1024) NULL COMMENT '归一化后的问题文本，用于去重和后续匹配',
  `matched_question_id` VARCHAR(64) NULL COMMENT '最接近但未达到回答阈值的可回答问题 ID',
  `match_score` DECIMAL(6, 5) NULL COMMENT '最接近问题的相似度分数',
  `miss_reason` VARCHAR(64) NOT NULL DEFAULT 'NO_MATCH' COMMENT '未回答原因：NO_MATCH=无匹配；LOW_CONFIDENCE=置信度低；TOOL_UNSUPPORTED=工具不支持；PERMISSION_DENIED=权限不足；ERROR=系统异常',
  `status` VARCHAR(32) NOT NULL DEFAULT 'PENDING' COMMENT '处理状态：PENDING=待处理；RESOLVED=已转为可回答；IGNORED=忽略',
  `resolved_question_id` VARCHAR(64) NULL COMMENT '处理后生成或关联的可回答问题 ID',
  `manual_answer` LONGTEXT NULL COMMENT '人工补充的答案草稿，确认后可转入可回答问题库',
  `occur_count` BIGINT NOT NULL DEFAULT 1 COMMENT '相似未回答问题累计出现次数',
  `first_ask_time` BIGINT NOT NULL COMMENT '第一次提问时间（毫秒时间戳）',
  `last_ask_time` BIGINT NOT NULL COMMENT '最后一次提问时间（毫秒时间戳）',
  `remark` VARCHAR(1024) NULL COMMENT '处理备注',
  `create_user` VARCHAR(64) NULL COMMENT '创建人 ID',
  `update_user` VARCHAR(64) NULL COMMENT '最后修改人 ID',
  `create_time` BIGINT NOT NULL COMMENT '创建时间（毫秒时间戳）',
  `update_time` BIGINT NOT NULL COMMENT '更新时间（毫秒时间戳）',
  INDEX idx_ai_agent_unanswered_org_status (`organization_id`, `status`, `last_ask_time`),
  INDEX idx_ai_agent_unanswered_question (`organization_id`, `normalized_question`(191)),
  INDEX idx_ai_agent_unanswered_source (`session_id`, `message_id`),
  INDEX idx_ai_agent_unanswered_resolved (`resolved_question_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci COMMENT='AI Agent 未回答问题池：保存无法回答的问题、未命中原因和人工处理状态';
