ALTER TABLE customer
    MODIFY COLUMN wecom_external_id VARCHAR(255) NULL COMMENT '客户企业微信ID',
    MODIFY COLUMN email VARCHAR(255) NULL COMMENT '邮箱',
    MODIFY COLUMN full_name VARCHAR(255) NULL COMMENT '客户全称',
    MODIFY COLUMN credit_limit VARCHAR(255) NULL COMMENT '信用额度',
    MODIFY COLUMN customs_code VARCHAR(255) NULL COMMENT '海关编码',
    MODIFY COLUMN region VARCHAR(255) NULL COMMENT '地区',
    MODIFY COLUMN phone VARCHAR(255) NULL COMMENT '电话',
    MODIFY COLUMN address VARCHAR(512) NULL COMMENT '地址',
    MODIFY COLUMN remark VARCHAR(512) NULL COMMENT '备注';
